name: maze_vpn
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  auto_route: ^8.2.0
  collection: ^1.18.0
  cross_connectivity: ^3.2.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dio: ^5.5.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  email_validator: ^3.0.0
  envied: ^0.5.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  hive: ^2.2.3
  hooks_riverpod: ^2.5.1
  injectable: ^2.4.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0
  envied_generator: ^0.5.4
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/animations/
    - assets/flags/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true
